parameters:
  router.request_context.scheme: 'https'
  asset.request_context.secure: true

  email_admin: '%email_admin%'
  images_directory: '%kernel.project_dir%/public/uploads/images'

  timezone: '%env(APP_TIMEZONE)%'

  env(MENU_LONG): "STISLA"
  env(MENU_SHORT): "ST"
  env(TITLE): "Stisla Admin"
  env(SITE_NAME): "CHAPTER-THREE PRESENTS"
  env(VERSION): "Version 3.1"
  env(GA_TRACKING_ID): ""

twig:
  paths:
  #'%kernel.project_dir%/vendor/symfony/web-profiler-bundle/Resources/views/Profiler': 'c3'

  globals:
    menu_long: '%env(MENU_LONG)%'
    menu_short: '%env(MENU_SHORT)%'
    title: '%env(TITLE)%'
    site_name: '%env(SITE_NAME)%'
    version: '%env(VERSION)%'
    ga_tracking_id: '%env(GA_TRACKING_ID)%'

  date:
    timezone: Asia/Tokyo

framework:
  #  error_controller: App\Controller\Defaults\ExceptionController::showException
  ide: "phpstorm://open?file=%%f&line=%%l"

monolog:
  channels: ['alert','info']

  handlers:

    slack-error:
      type: slackwebhook
      webhook_url: '' #'https://hooks.slack.com/services/*********/*********/************************'
      channel: '#alert'
      channels: ['alert']
      #- [bot_name]: defaults to Monolog
      #- [icon_emoji]: defaults to null
      #- [use_attachment]: bool, defaults to true
      #- [use_short_attachment]: bool, defaults to false
      #- [include_extra]: bool, defaults to false
      #- [level]: level name or int value, defaults to DEBUG
      #- [bubble]: bool, defaults to true
      #- [timeout]: float
      #- [connection_timeout]: float

    slack:
      type:        slackwebhook
      webhook_url: 'https://hooks.slack.com/services/*********/***********/************************'
      channel:     '#general'
      bot_name:    'slack_bot_name'
      icon_emoji:  ":heavy_check_mark:" # ✅
      level:       debug
      include_extra: true
      channels:    ['info']
