parameters:
  timezone: '%env(APP_TIMEZONE)%'

  env(MENU_LONG): ""
  env(MENU_SHORT): ""
  env(TITLE): ""
  env(SITE_NAME): ""
  env(VERSION): "1.0"
  env(GA_TRACKING_ID): "1.0"

twig:
  paths:
  #'%kernel.project_dir%/vendor/symfony/web-profiler-bundle/Resources/views/Profiler': 'c3'

  globals:
    menu_long: '%env(MENU_LONG)%'
    menu_short: '%env(MENU_SHORT)%'
    title: '%env(TITLE)%'
    site_name: '%env(SITE_NAME)%'
    version: '%env(VERSION)%'
    ga_tracking_id: '%env(GA_TRACKING_ID)%'