#services:
#  ChapterThree\C3Bundle\Command\c3ConfigCommand:
#    tags:
#      name: console.command
#      command: c3:config
#    class: ChapterThree\C3Bundle\Command\c3ConfigCommand
#    public: true
#
#twig:
#  globals:
#    menu_long: '%env(MENU_LONG)%'
#    menu_short: '%env(MENU_SHORT)%'
#    title: '%env(TITLE)%'
#    site_name: '%env(SITE_NAME)%'
#    version: '%env(VERSION)%'
#    ga_tracking_id: '%env(GA_TRACKING_ID)%'
#
#  paths:
#    #'%kernel.project_dir%/vendor/chapter-three-company/stisla-twig/Resources/templates': 'c3'
#    '../../Resources/templates': 'c3'

#parameters:
#  c3.ga_tracking_id: ''


#twig_component:
#  anonymous_template_directory: 'components/'
#  defaults:
#    #ChapterThree\C3Bundle\Twig\Components\: '%kernel.project_dir%/vendor/chapter-three-company/c3-bundle/templates/components/'
#    # long form
#    ChapterThree\C3Bundle\Twig\Components\:
#      #template_directory: '%kernel.project_dir%/vendor/chapter-three-company/c3-bundle/templates/components/'
#      template_directory: './components/'
#      # component names will have an extra "Pizza:" prefix
#      #    App\Pizza\Components\Alert => Pizza:Alert
#      #    App\Pizza\Components\Button\Primary => Pizza:Button:Primary
#      #name_prefix: C3