twig:
  globals:
    menu_long: '%env(MENU_LONG)%'
    menu_short: '%env(MENU_SHORT)%'
    title: '%env(TITLE)%'
    site_name: '%env(SITE_NAME)%'
    version: '%env(VERSION)%'
    ga_tracking_id: '%env(GA_TRACKING_ID)%'
