<?php

namespace ChapterThree\C3Bundle;

use ChapterThree\C3Bundle\DependencyInjection\C3Extension;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\AbstractBundle;
use \Symfony\Component\DependencyInjection\Extension\ExtensionInterface;
use Symfony\Runtime\Symfony\Component\Console\Input\InputInterfaceRuntime;
use Symfony\Runtime\Symfony\Component\Console\Output\OutputInterfaceRuntime;

class C3Bundle extends AbstractBundle
{
    public function __construct(
        private InputInterface $input,
        private OutputInterface $output
    )
    {
    }

    public function getContainerExtension(): ?ExtensionInterface
    {
        return new C3Extension();
    }

    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $io = new SymfonyStyle($this->input, $this->output);


    }
    /*    public function getPath(): string
        {
            return dirname(__DIR__);
        }*/
}